### ISSUE TITLE
Add 7 gen Wild Opponent Pokemon Dumping

### ISSUE THREAD

**Issue by Real96** [jackmax/PKMN-NTR#2]
Can you add the function in 7 gen for dumping opponent Pokemon during wild battle to check IVs, Nature and the other things? This would be really useful, aslo for softresetting

**Comment by jackmax** [comment]
Closed by e484daa. Ask @drgoku282 to integrate it into the soft-reset bot, I'm not the bot guy.

**Comment by Real96** [comment]
I love you <3
